apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deploy-file-auto-update-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ductri179/argo-cd-config.git
    targetRevision: HEAD
    path: file-auto-update
  destination:
    server: https://kubernetes.default.svc
    namespace: eis-demo