apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-auto-update-deployment
spec:
  selector:
    matchLabels:
      app: file-auto-update
  replicas: 1
  template:
    metadata: 
      labels:
        app: file-auto-update
    spec:
      volumes: 
        - name: demo-pv-storage
          persistentVolumeClaim:
            claimName: demo-pv-claim
      containers:
        - name: file-auto-update
          image: oscartran17/file-auto-update:10.0
          ports:
          - containerPort: 8080
          volumeMounts:
            - mountPath: "/demo-data"
              name: demo-pv-storage
          env:
            - name: DB_PATH
              valueFrom:
                configMapKeyRef:
                  name: demo-config
                  key: db.path