apiVersion: apps/v1
kind: Deployment
metadata:
  name: geo-deployment
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  selector:
    matchLabels:
      app: geo
  replicas: 1
  template:
    metadata: 
      labels:
        app: geo
    spec:
      volumes: 
        - name: demo-pv-storage
          persistentVolumeClaim:
            claimName: demo-pv-claim
      containers:
        - name: geo
          image: oscartran17/geo-demo:1.0
          ports:
          - containerPort: 8080
          volumeMounts:
            - mountPath: "/data-tri"
              name: demo-pv-storage
          env:
            - name: FILE_LOCATION
              valueFrom:
                configMapKeyRef:
                  name: geo-config
                  key: file.location