apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
spec:
  selector:
    matchLabels:
      app: demo
  replicas: 2
  template:
    metadata: 
      labels:
        app: demo
    spec:
      volumes: 
        - name: demo-pv-storage
          persistentVolumeClaim:
            claimName: demo-pv-claim
      containers:
        - name: demo
          image: oscartran17/demo:1.0
          ports:
          - containerPort: 8080
          volumeMounts:
            - mountPath: "/demo-data"
              name: demo-pv-storage
          env:
            - name: FILE_LOCATION
              valueFrom:
                configMapKeyRef:
                  name: demo-config
                  key: file.location